[package]
name = "tree_magic"
version = "0.1.1"
authors = ["Aaron Hancock <aahancoc@umflint.edu>"]
description = "Determines the MIME type of a file by traversing a filetype tree."
repository = "https://github.com/aahancoc/tree_magic/"
documentation = "https://docs.rs/tree_magic/"
readme = "README.md"
keywords = ["mime", "filesystem", "media-types"]
license = "MIT"

[dependencies]
petgraph = "^0"
nom = "^2"
lazy_static = "^0.2"
itertools = "^0.6"

tabwriter = { version = "^1", optional = true }
clap = { version = "^2", optional = true }

[features]
cli = ["clap", "tabwriter"]
staticmime = []     # Use &'static str for output insead of String.
sys_fdo_magic = []  # Use system magic file for fdo_magic checker
default = ["cli"]

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

[[bin]]
required-features = ["cli"]
name = "tmagic"
path = "src/main.rs"
